[package]
name = "gb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.4"
fundsp = "0.15.0"
clap = { version = "4.4.9", features = ["derive"] }
bitflags = "2.4.1"
log = "0.4.20"